" ----------------------------------------------------------------------------
" KEY MAPS
" ----------------------------------------------------------------------------

" Set leader key
let mapleader="\<SPACE>"

"Unbind arrow keys
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>
inoremap <up>    <nop>
inoremap <down>  <nop>
inoremap <left>  <nop>
inoremap <right> <nop>

"Toggle search higlight
nmap <leader>q :set hlsearch!<CR>

"Fix linewise behaviour
nnoremap j gj
nnoremap k gk

"Return to last window 
nmap <C-e> :e#<CR>

"Toggle display number
nmap <leader>l :setlocal number!<CR>

" ----------------------------------------------------------------------------
" OPTIONS
" ----------------------------------------------------------------------------

"Set basic options
set showmatch
set number
set expandtab
set tabstop=4
set shiftwidth=4

"Set search options
set incsearch
set ignorecase
set smartcase
set hlsearch

"Set term colors
set termguicolors

" ----------------------------------------------------------------------------
" PLUGIN SETTINGS
" ----------------------------------------------------------------------------

" Specify a directory for plugins
call plug#begin('~/.nvim/plugged')

" Color theme
Plug 'morhetz/gruvbox'

" Fuzzy finder
Plug 'junegunn/fzf.vim'
Plug '~/.fzf'

" Initialize plugin system
call plug#end()

"Set colorscheme
let g:gruvbox_contrast_dark = 'hard' "Hard contrast
colorscheme gruvbox
set background=dark "Dark theme

