"Unbind arrow keys
nnoremap <up>    <nop>
nnoremap <down>  <nop>
nnoremap <left>  <nop>
nnoremap <right> <nop>
inoremap <up>    <nop>
inoremap <down>  <nop>
inoremap <left>  <nop>
inoremap <right> <nop>

"Search configuration
set incsearch
set ignorecase
set smartcase
set hlsearch
nmap \q :nohlsearch<CR>

"Fix linewise behaviour
nmap j gj
nmap k gk

"Return to last window 
nmap <C-e> :e#<CR>

"Utilities
nmap \l :setlocal number!<CR>
nmap \o :set paste!<CR>

